/**
 * Varsayılan ürün verisi. Hem seed (prisma/seed.ts) hem de veritabanına
 * ulaşılamadığında sitenin boş katalog göstermemesi için kullanılır.
 */
export const defaultProducts = [
  {
    slug: "bakir-katot",
    code: "CU-CAT-99",
    category: "copper",
    badge: "Grade-A",
    badgeHighlight: true,
    image: "/images/product-copper-cathode.jpg",
    nameTr: "Bakır Katot",
    nameEn: "Copper Cathode",
    subtitleTr: "Elektrolitik Bakır",
    subtitleEn: "Electrolytic Copper",
    descriptionTr: "%99.99 saflık oranında LME tescilli standart elektrolitik bakır plakalar. Kablo ve iletken sanayisine uygun.",
    descriptionEn: "LME-registered standard electrolytic copper plates at 99.99% purity. Suitable for the cable and conductor industry.",
    detailsTr:
      "Grade-A bakır katotlarımız, uluslararası LME kayıtlı rafinerilerden tedarik edilir ve her sevkiyat spektro analiz raporu ile birlikte teslim edilir.\n\nKablo, filmaşin, döküm ve alaşım üretimi için ideal hammaddedir.",
    detailsEn:
      "Our Grade-A copper cathodes are sourced from internationally LME-registered refineries and each shipment is delivered with a spectro analysis report.\n\nThe ideal raw material for cable, wire rod, casting and alloy production.",
    specCode: "CU-CAT-A",
    specMaterialTr: "Elektrolitik Bakır Katot",
    specMaterialEn: "Electrolytic Copper Cathode",
    specPurity: "Cu ≥ %99.9935",
    specFormTr: "Plaka (~100kg / adet)",
    specFormEn: "Plate (~100kg / piece)",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "aluminyum-kulce",
    code: "AL-INGOT-01",
    category: "aluminum",
    badge: "P1020 / A7",
    image: "/images/product-aluminum-ingot.jpg",
    nameTr: "Alüminyum Külçe",
    nameEn: "Aluminium Ingot",
    subtitleTr: "Birincil Metal",
    subtitleEn: "Primary Metal",
    descriptionTr: "Otomotiv, enjeksiyon döküm ve profil sanayisi için yüksek saflıkta P1020 standardı külçeler.",
    descriptionEn: "High-purity P1020 standard ingots for the automotive, die-casting and profile industries.",
    specCode: "AL-P1020",
    specMaterialTr: "Alüminyum Külçe Primary",
    specMaterialEn: "Primary Aluminium Ingot",
    specPurity: "Al ≥ %99.70",
    specFormTr: "Külçe Paket (~15-20kg)",
    specFormEn: "Ingot Bundle (~15-20kg)",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "aluminyum-billet",
    code: "AL-BIL-6063",
    category: "aluminum",
    badge: "EN AW-6063",
    image: "/images/product-aluminum-billet.jpg",
    nameTr: "Alüminyum Billet",
    nameEn: "Aluminium Billet",
    subtitleTr: "Ekstrüzyon Billet",
    subtitleEn: "Extrusion Billet",
    descriptionTr: "6060, 6063 ve 6082 alaşımlı homojenize ekstrüzyon takozları. Mimari ve endüstriyel profiller için.",
    descriptionEn: "Homogenised 6060, 6063 and 6082 alloy extrusion billets for architectural and industrial profiles.",
    specCode: "AL-BIL-63",
    specMaterialTr: "Alüminyum Ekstrüzyon Billet",
    specMaterialEn: "Aluminium Extrusion Billet",
    specPurity: "AlMgSi 6063 / 6060",
    specFormTr: "Çap: 127mm - 203mm",
    specFormEn: "Diameter: 127mm - 203mm",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "bakir-filmasin",
    code: "CU-ROD-8MM",
    category: "copper",
    badge: "8.00 mm",
    image: "/images/product-copper-rod.jpg",
    nameTr: "Bakır Filmaşin",
    nameEn: "Copper Wire Rod",
    subtitleTr: "Filmaşin & Alaşım",
    subtitleEn: "Wire Rod & Alloy",
    descriptionTr: "Sürekli döküm 8mm ETP bakır filmaşin, bronz ve pirinç alaşım çubuklar ile sanayi hammaddeleri.",
    descriptionEn: "Continuous cast 8mm ETP copper wire rod, bronze and brass alloy bars and industrial raw materials.",
    specCode: "CU-ROD-08",
    specMaterialTr: "ETP Bakır Filmaşin",
    specMaterialEn: "ETP Copper Wire Rod",
    specPurity: "Cu ≥ %99.90 (101% IACS)",
    specFormTr: "Rulo Kangal (~3-5 MT)",
    specFormEn: "Coil (~3-5 MT)",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "polipropilen-pp",
    code: "PL-PP",
    category: "plastic",
    inStock: false,
    badge: "PP",
    image: "/images/product-plastic-granules.jpg",
    nameTr: "Polipropilen (PP)",
    nameEn: "Polypropylene (PP)",
    subtitleTr: "Homopolimer ve Kopolimer",
    subtitleEn: "Homopolymer and Copolymer",
    descriptionTr: "Enjeksiyon, film ve elyaf uygulamaları için homopolimer ve kopolimer PP granül. Sınıf ve MFI teklif aşamasında teyit edilir.",
    descriptionEn: "Homopolymer and copolymer PP pellets for injection, film and fibre applications. Grade and MFI are confirmed at the quotation stage.",
    detailsTr:
      "Ürün sınıfı, eriyik akış indeksi (MFI) ve üretici menşei her teklifte yazılı olarak bildirilir.\n\nEnjeksiyon kalıplama, BOPP/CPP film ve elyaf üretimi için uygun kaliteler.",
    detailsEn:
      "Grade, melt flow index (MFI) and producer origin are stated in writing with every offer.\n\nGrades suited to injection moulding, BOPP/CPP film and fibre production.",
    specCode: "PL-PP",
    specMaterialTr: "Polipropilen Granül",
    specMaterialEn: "Polypropylene Pellets",
    specPurity: "PP-H / PP-R / PP-B",
    specFormTr: "Granül, 25 kg torba / big bag",
    specFormEn: "Pellets, 25 kg bags / big bags",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "yuksek-yogunluklu-polietilen-hdpe",
    code: "PL-HDPE",
    category: "plastic",
    inStock: false,
    badge: "HDPE",
    image: "/images/product-plastic-hdpe.jpg",
    nameTr: "Yüksek Yoğunluklu Polietilen (HDPE)",
    nameEn: "High-Density Polyethylene (HDPE)",
    subtitleTr: "Enjeksiyon · Şişirme · Boru",
    subtitleEn: "Injection · Blow Moulding · Pipe",
    descriptionTr: "Enjeksiyon, şişirme ve boru/profil ekstrüzyonu için HDPE granül. Sınıf, yoğunluk ve MFI teklif aşamasında teyit edilir.",
    descriptionEn: "HDPE pellets for injection, blow moulding and pipe/profile extrusion. Grade, density and MFI are confirmed at the quotation stage.",
    detailsTr:
      "Ürün sınıfı, yoğunluk, MFI ve üretici menşei her teklifte yazılı olarak bildirilir.\n\nKasa ve kap enjeksiyonu, şişe ve bidon şişirme ile boru ve profil ekstrüzyonu için uygun kaliteler.",
    detailsEn:
      "Grade, density, MFI and producer origin are stated in writing with every offer.\n\nGrades suited to crate and container injection, bottle and jerrycan blow moulding, and pipe and profile extrusion.",
    specCode: "PL-HDPE",
    specMaterialTr: "Yüksek Yoğunluklu Polietilen Granül",
    specMaterialEn: "High-Density Polyethylene Pellets",
    specPurity: "PE-HD",
    specFormTr: "Granül, 25 kg torba / big bag",
    specFormEn: "Pellets, 25 kg bags / big bags",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
  {
    slug: "alcak-yogunluklu-polietilen-ldpe",
    code: "PL-LDPE",
    category: "plastic",
    inStock: false,
    badge: "LDPE",
    image: "/images/product-plastic-ldpe.jpg",
    nameTr: "Alçak Yoğunluklu Polietilen (LDPE)",
    nameEn: "Low-Density Polyethylene (LDPE)",
    subtitleTr: "Film · Ambalaj",
    subtitleEn: "Film · Packaging",
    descriptionTr: "Film, ambalaj ve kaplama uygulamaları için LDPE granül. Sınıf, yoğunluk ve MFI teklif aşamasında teyit edilir.",
    descriptionEn: "LDPE pellets for film, packaging and coating applications. Grade, density and MFI are confirmed at the quotation stage.",
    detailsTr:
      "Ürün sınıfı, yoğunluk, MFI ve üretici menşei her teklifte yazılı olarak bildirilir.\n\nŞişirme film, shrink ve streç film, ekstrüzyon kaplama için uygun kaliteler.",
    detailsEn:
      "Grade, density, MFI and producer origin are stated in writing with every offer.\n\nGrades suited to blown film, shrink and stretch film, and extrusion coating.",
    specCode: "PL-LDPE",
    specMaterialTr: "Alçak Yoğunluklu Polietilen Granül",
    specMaterialEn: "Low-Density Polyethylene Pellets",
    specPurity: "PE-LD",
    specFormTr: "Granül, 25 kg torba / big bag",
    specFormEn: "Pellets, 25 kg bags / big bags",
    specUnitTr: "Metrik Ton (MT)",
    specUnitEn: "Metric Ton (MT)",
  },
];
