/**
 * Varsayılan ana slider slaytları (bakır / alüminyum / plastik).
 * Seed ve scripts/reset-slides.ts tarafından kullanılır.
 */
export const defaultSlides = [
  {
    image: "/images/product-copper-cathode.jpg",
    eyebrowTr: "Bakır",
    eyebrowEn: "Copper",
    titleTr: "Bakır ve alüminyum,",
    titleEn: "Copper and aluminium,",
    highlightTr: "her partisi belgeli.",
    highlightEn: "certified by the lot.",
    descriptionTr: "Grade A bakır katot, P1020 alüminyum külçe, 6000 serisi billet ve bakır filmaşin. LME tescilli rafinerilerden tedarik, LME bazlı fiyat ve her sevkiyatta spektro analiz raporuyla İstanbul'dan teslim.",
    descriptionEn: "Grade A copper cathode, P1020 aluminium ingot, 6000-series billet and copper wire rod. Sourced from LME-registered refineries, priced against the LME and delivered from Istanbul with a spectro analysis report on every shipment.",
    primaryLabelTr: "Teklif İsteyin",
    primaryLabelEn: "Request a Quote",
    primaryHref: "/quote",
    secondaryLabelTr: "Ürünleri İnceleyin",
    secondaryLabelEn: "Explore Products",
    secondaryHref: "/products",
  },
  {
    image: "/images/product-aluminum-ingot.jpg",
    eyebrowTr: "Alüminyum",
    eyebrowEn: "Aluminium",
    titleTr: "Alüminyum külçe ve billet,",
    titleEn: "Aluminium ingot and billet,",
    highlightTr: "şartnamenize göre.",
    highlightEn: "to your specification.",
    descriptionTr: "Döküm, otomotiv ve profil üreticileri için P1020 birincil alüminyum külçe ve homojenize 6000 serisi ekstrüzyon billeti; her partide analizle.",
    descriptionEn: "P1020 primary aluminium ingot and homogenised 6000-series extrusion billet for casting, automotive and profile producers, with analysis on every lot.",
    primaryLabelTr: "Teklif İsteyin",
    primaryLabelEn: "Request a Quote",
    primaryHref: "/quote",
    secondaryLabelTr: "Alüminyum",
    secondaryLabelEn: "Aluminium",
    secondaryHref: "/products?category=aluminum",
  },
  {
    image: "/images/product-plastic-granules.jpg",
    eyebrowTr: "Plastik",
    eyebrowEn: "Plastic",
    titleTr: "Plastik hammadde,",
    titleEn: "Plastic raw materials,",
    highlightTr: "aynı disiplinle.",
    highlightEn: "with the same discipline.",
    descriptionTr: "Granül plastik hammaddelerde de metaldeki yöntem: belgeli parti, net spesifikasyon ve yazılı teklif.",
    descriptionEn: "Granular plastic raw materials handled the way we handle metal: documented lots, a clear specification and a written offer.",
    primaryLabelTr: "Teklif İsteyin",
    primaryLabelEn: "Request a Quote",
    primaryHref: "/quote",
    secondaryLabelTr: "Plastik Hammadde",
    secondaryLabelEn: "Plastic Raw Materials",
    secondaryHref: "/products?category=plastic",
  },
];
